apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rnaseq-mini.fullname" . }}-results
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rnaseq-mini.labels" . | nindent 4 }}
    app: rnaseq-mini
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.results.size | quote }}
  storageClassName: {{ include "rnaseq-mini.storageClass" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rnaseq-mini.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rnaseq-mini.labels" . | nindent 4 }}
    app: rnaseq-mini
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size | quote }}
  storageClassName: {{ include "rnaseq-mini.storageClass" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rnaseq-mini.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rnaseq-mini.labels" . | nindent 4 }}
    app: rnaseq-mini
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  storageClassName: {{ include "rnaseq-mini.storageClass" . }}















